[package]
name = "cached-fn"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
repository = "https://github.com/makcandrov/cached-fn"
homepage = "https://github.com/makcandrov/cached-fn"
license = "MIT OR Apache-2.0"
keywords = ["cached", "fn"]

[dependencies]
